grant all privileges to BASE;
grant dba to BASE;
grant execute on dbms_pipe to BASE;
grant execute on dbms_lock to BASE;
grant execute on dbms_rls to BASE;
grant all on dbms_rls to BASE;
grant select on dba_tables to BASE;
grant select any dictionary to BASE;
grant all on v_$session to BASE;
grant all on v_$parameter to BASE;
grant all on obj$ to BASE;
grant all on objauth$ to BASE;
grant all on user$ to BASE;
grant all on sysauth$ to BASE;
grant all on dba_indexes to BASE;
grant all on dba_objects to BASE;
grant all on source$ to BASE;
grant all on dbms_pipe to BASE;
grant all on dbms_aq to BASE;
grant all on dbms_lock to BASE;
grant all on dbms_sql to BASE;

grant all privileges to COMMON;
grant dba to COMMON;
grant execute on dbms_pipe to COMMON;
grant execute on dbms_lock to COMMON;
grant execute on dbms_rls to COMMON;
grant all on dbms_rls to COMMON;
grant select on dba_tables to COMMON;
grant select any dictionary to COMMON;
grant all on v_$session to COMMON;
grant all on v_$parameter to COMMON;
grant all on obj$ to COMMON;
grant all on objauth$ to COMMON;
grant all on user$ to COMMON;
grant all on sysauth$ to COMMON;
grant all on dba_indexes to COMMON;
grant all on dba_objects to COMMON;
grant all on source$ to COMMON;
grant all on dbms_pipe to COMMON;
grant all on dbms_aq to COMMON;
grant all on dbms_lock to COMMON;
grant all on dbms_sql to COMMON;

grant all privileges to DEV;
grant dba to DEV;
grant execute on dbms_pipe to DEV;
grant execute on dbms_lock to DEV;
grant execute on dbms_rls to DEV;
grant all on dbms_rls to DEV;
grant select on dba_tables to DEV;
grant select any dictionary to DEV;
grant all on v_$session to DEV;
grant all on v_$parameter to DEV;
grant all on obj$ to DEV;
grant all on objauth$ to DEV;
grant all on user$ to DEV;
grant all on sysauth$ to DEV;
grant all on dba_indexes to DEV;
grant all on dba_objects to DEV;
grant all on source$ to DEV;
grant all on dbms_pipe to DEV;
grant all on dbms_aq to DEV;
grant all on dbms_lock to DEV;
grant all on dbms_sql to DEV;
