#!/bin/bash

# This script will create database objects for user BASE
# Author: Yuriy Lazutin
# Site: lazutin.info
# Location: Tomsk, Siberia
# Creation: 2021-apr-23
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

source ./rollpack-cmn
source ./print-info
source ./getpass "BASE"

sqlplus "BASE/${BASE_PASS}" &> "${LOGDIR}/add-BASE-objects-script.log" <<EOF
set verify off
set echo on
spool ${LOGDIR}/add-BASE-objects.log append
@BASE.gForm.ddl.sql;
@BASE.gList.ddl.sql;
@BASE.gTree.ddl.sql;
@BASE.primary_filter.ddl.sql;
@BASE.secondary_filter.ddl.sql;
@BASE.class.ddl.sql;
@BASE.widget.ddl.sql;
@BASE.description.ddl.sql;
@BASE.property.ddl.sql;
@BASE.text_translation.ddl.sql;
@BASE.clob_translation.ddl.sql;
@BASE.solution.ddl.sql;
@BASE.subset.ddl.sql;

@BASE.sequences.ddl.sql;

@BASE.tIntegerTable.ddl.sql;
@BASE.czVector.typ;
@BASE.czStack.typ;
@BASE.cComplexNumber.typ;
@BASE.cz2DMatrix.typ;
@BASE.cSQLQuery.typ;
@BASE.cRobot.typ;

@BASE.libc_l.ddl "${ORACLE_BASE}/oradata/${ORACLE_SID}";

@BASE.iBase.spc;
@BASE.iClass.spc;
@BASE.iDescription.spc;
@BASE.igForm.spc;
@BASE.igList.spc;
@BASE.igTree.spc;
@BASE.iText_Translation.spc;
@BASE.iCLOB_Translation.spc;
@BASE.iPrimary_Filter.spc;
@BASE.iSecondary_Filter.spc;
@BASE.iSolution.spc;
@BASE.iProperty.spc;
@BASE.iSubset.spc;
@BASE.iWidget.spc;
@BASE.math_utl.spc;
@BASE.random_utl.spc;

@BASE.iClass.bdy;
@BASE.iDescription.bdy;
@BASE.igForm.bdy;
@BASE.igList.bdy;
@BASE.igTree.bdy;
@BASE.iText_Translation.bdy;
@BASE.iCLOB_Translation.bdy;
@BASE.iPrimary_Filter.bdy;
@BASE.iSecondary_Filter.bdy;
@BASE.iSolution.bdy;
@BASE.iProperty.bdy;
@BASE.iSubset.bdy;
@BASE.iWidget.bdy;
@BASE.math_utl.bdy;
@BASE.random_utl.bdy;

@BASE.views.sql;

spool off
exit
EOF


./mask-pass "${LOGDIR}/add-BASE-objects-script.log"
./mask-pass "${LOGDIR}/add-BASE-objects.log"

PrintInfo "Creating BASE objects"
