#!/bin/bash

# This script will add new users into database
# Author: Yuriy Lazutin
# Site: lazutin.info
# Location: Tomsk, Siberia
# Creation: 2021-apr-12
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

source ./rollpack-cmn
source ./print-info
source ./getpass "SYS"

if [ "${DB_ENABLE_DATABASE_VAULT^^}" == "Y" ]; then
  if [ ! -z "${VAULT_ACCMAN^^}" ] && [ "${VAULT_ACCMAN^^}" != "${VAULT_OWNER^^}" ]; then
    SCRIPT_EXECUTOR="${VAULT_ACCMAN^^}"
  else
    SCRIPT_EXECUTOR="${VAULT_OWNER^^}"
  fi

  source ./getpass "${SCRIPT_EXECUTOR}"

  sqlplus "${SCRIPT_EXECUTOR}/$( eval echo "\$${SCRIPT_EXECUTOR^^}_PASS" )" &> "${LOGDIR}/add-users-script.log" <<EOF
  set verify off
  set echo on
  spool ${LOGDIR}/add-users.log append
  @add-users.sql ${SYS_PASS};
  spool off
  exit
EOF

else

  sqlplus "SYS/${SYS_PASS}" as SYSDBA &> "${LOGDIR}/add-users-script.log" <<EOF
  set verify off
  set echo on
  spool ${LOGDIR}/add-users.log append
  @add-users.sql ${SYS_PASS};
  spool off
  exit
EOF

fi

# Add grantes to new users
sqlplus "SYS/${SYS_PASS}" as SYSDBA &>> "${LOGDIR}/add-users-script.log" <<EOF
set verify off
set echo on
spool ${LOGDIR}/add-users.log append
@add-users-rights.sql;
spool off
exit
EOF

./mask-pass "${LOGDIR}/add-users-script.log"
./mask-pass "${LOGDIR}/add-users.log"

PrintInfo "Creating new users"
