CREATE SMALLFILE TABLESPACE "BASE" DATAFILE '&1/base.dat'
SIZE 100M
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
DEFAULT NOCOMPRESS;

ALTER DATABASE
DATAFILE '&1/base.dat'
AUTOEXTEND ON
MAXSIZE UNLIMITED;

CREATE SMALLFILE TABLESPACE "COMMON" DATAFILE '&1/common.dat'
SIZE 300M
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
DEFAULT NOCOMPRESS;

ALTER DATABASE
DATAFILE '&1/common.dat'
AUTOEXTEND ON
MAXSIZE UNLIMITED;

CREATE SMALLFILE TABLESPACE "DEV" DATAFILE '&1/dev.dat'
SIZE 10M
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
DEFAULT NOCOMPRESS;

ALTER DATABASE
DATAFILE '&1/dev.dat'
AUTOEXTEND ON
MAXSIZE UNLIMITED;
