#!/bin/bash

# This script will mask passwords in log files.
# Author: Yuriy Lazutin
# Site: lazutin.info
# Location: Tomsk, Siberia
# Creation: 2021-apr-12
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

if [ ! -z "${SYS_PASS}" ]; then
  sed -i "s/${SYS_PASS}/#################/g" "${1}"
fi
