#!/bin/bash

# This script will install database for ybusiness software.
# Author: Yuriy Lazutin
# Site: lazutin.info
# Location: Tomsk, Siberia
# Creation: 2021-apr-03
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

SRCROOT_DIR=$( dirname ${0} )
if [ "${SRCROOT_DIR}" == "." ]; then
  SRCROOT_DIR=$( pwd )
fi

if [ -z "${YBUSINESS_SETUP_LEVEL}" ]; then
  export YBUSINESS_SETUP_LEVEL="full"
  source ./conf
fi



# 000000000000
echo "Installing empty database (level zero)"
source "${SRCROOT_DIR}/rollpacks/000000000000/checkcfg"
sudo su - ${ORACLE_OWNER} sh -c "
cd \"${SRCROOT_DIR}/rollpacks/000000000000\"
./install"
sudo sh -c "cd \"${SRCROOT_DIR}/rollpacks/000000000000\"
./root"


# 000100000000
echo "Installing initial database"
source "${SRCROOT_DIR}/rollpacks/000100000000/checkcfg"
sudo su - ${ORACLE_OWNER} sh -c "
cd \"${SRCROOT_DIR}/rollpacks/000100000000\"
./install"





################### Done ! #####################

echo
echo -e "\033[1;32m${ORACLE_SID} database was successfully installed. Press any key to exit\033[0m"
read v_dummy
