#!/bin/bash

# This script will create new database for ybusiness software.
# Author: Yuriy Lazutin
# Site: lazutin.info
# Location: Tomsk, Siberia
# Creation: 2021-apr-08
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

if [ -z "${YBUSINESS_SETUP_LEVEL}" ]; then
  export YBUSINESS_SETUP_LEVEL="script"
  source ../../conf
fi

source ./print-info
source ./getpass "SYS"
source ./getpass "SYSTEM"

sqlplus "sys/${SYS_PASS}" as SYSDBA &> "${LOGDIR}/add-database-script.log" <<EOF
set verify off
set echo on
spool ${LOGDIR}/add-database.log append
startup nomount pfile="${INIT_ORA}";

CREATE DATABASE "${ORACLE_SID}"
MAXINSTANCES 8
MAXLOGHISTORY 1
MAXLOGFILES 16
MAXLOGMEMBERS 3
MAXDATAFILES 100
DATAFILE '${ORACLE_BASE}/oradata/${ORACLE_SID}/system01.dat' SIZE 700M REUSE AUTOEXTEND ON NEXT  10240K MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL
SYSAUX DATAFILE '${ORACLE_BASE}/oradata/${ORACLE_SID}/sysaux01.dat' SIZE 600M REUSE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED
SMALLFILE DEFAULT TEMPORARY TABLESPACE TEMP TEMPFILE '${ORACLE_BASE}/oradata/${ORACLE_SID}/temp01.dat' SIZE 20M REUSE AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
SMALLFILE UNDO TABLESPACE "UNDOTBS1" DATAFILE '${ORACLE_BASE}/oradata/${ORACLE_SID}/undotbs01.dat' SIZE 200M REUSE AUTOEXTEND ON NEXT  5120K MAXSIZE UNLIMITED
CHARACTER SET AL32UTF8
NATIONAL CHARACTER SET AL16UTF16
LOGFILE GROUP 1 ('${ORACLE_BASE}/oradata/${ORACLE_SID}/redo01.log') SIZE 51200K,
GROUP 2 ('${ORACLE_BASE}/oradata/${ORACLE_SID}/redo02.log') SIZE 51200K,
GROUP 3 ('${ORACLE_BASE}/oradata/${ORACLE_SID}/redo03.log') SIZE 51200K
USER SYS IDENTIFIED BY "${SYS_PASS}" USER SYSTEM IDENTIFIED BY "${SYSTEM_PASS}";
spool off
exit
EOF

PrintInfo "Creating new database"
