#!/bin/bash

# This script will add sqlplus repo into new database
# Author: Yuriy Lazutin
# Site: lazutin.info
# Location: Tomsk, Siberia
# Creation: 2021-apr-08
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

source ./print-info
source ./getpass "SYSTEM"

echo "Executing ${ORACLE_HOME}/sqlplus/admin/pupbld.sql"
sqlplus "system/${SYSTEM_PASS}" &> "${LOGDIR}/add-sqlplus-script.log" <<EOF
set verify off
set echo on

spool ${LOGDIR}/pupbld.sql.log append
@${ORACLE_HOME}/sqlplus/admin/pupbld.sql;
spool off

exit
EOF

echo "Executing ${ORACLE_HOME}/sqlplus/admin/help/hlpbld.sql helpus.sql"
sqlplus "system/${SYSTEM_PASS}" &>> "${LOGDIR}/add-sqlplus-script.log" <<EOF
set verify off
set echo on

spool ${LOGDIR}/hlpbld.sql.log append
@${ORACLE_HOME}/sqlplus/admin/help/hlpbld.sql helpus.sql;
spool off

exit
EOF

PrintInfo "Installing sqlplus repo"
