#!/bin/bash

# This script will enable archive log mode in database
# Author: Yuriy Lazutin
# Site: lazutin.info
# Location: Tomsk, Siberia
# Creation: 2021-apr-09
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

if [ -z "${YBUSINESS_SETUP_LEVEL}" ]; then
  export YBUSINESS_SETUP_LEVEL="script"
  source ../../conf
fi

source ./print-info

if [ "${DB_ENABLE_ARCHIVELOG^^}" == "Y" ]; then

  if [ -z "${INIT_ORA}" ]; then
    source ./mk-init.ora
  fi

  source ./getpass "SYS"

  echo "Enabling Archive log mode..."
  sqlplus "sys/${SYS_PASS}" as SYSDBA &> "${LOGDIR}/archive-log-script.log" <<EOF
  set verify off
  set echo on

  spool ${LOGDIR}/archive-log.log append
  shutdown immediate;
  startup mount pfile="${INIT_ORA}";
  alter database archivelog;
  alter database open;
  spool off

  exit
EOF

  PrintInfo "Enabling Archive log mode"

fi
