#!/bin/bash

# This script will install database for ybusiness software.
# Author: Yuriy Lazutin
# Site: lazutin.info
# Location: Tomsk, Siberia
# Creation: 2021-apr-03
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

source ./conf
source ./checkcfg

######################
# Check current user #
######################
echo -n "Check current user: "
if [ "$( whoami )" == "${ORACLE_OWNER}" ]; then
  echo -e "\033[1;32mDone\033[0m"
else
  echo -e "\033[1;31mFailed\033[0m"
  echo "This script should be executed under ${ORACLE_OWNER}!"
  exit 1
fi

./profile
./listener
./mk-init.ora
# sudo ./root
