#!/bin/bash

# This script will install database for ybusiness software.
# Author: Yuriy Lazutin
# Site: lazutin.info
# Location: Tomsk, Siberia
# Creation: 2021-apr-03
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

if [ -z "${YBUSINESS_SETUP_LEVEL}" ]; then
  export YBUSINESS_SETUP_LEVEL="rollpack"
  source ../../conf
fi

source ./checkcfg

# Check current user (should be oracle, or sombody from dba group)
echo -n "Check current user: "
if [ "$( whoami )" == "${ORACLE_OWNER}" ]; then
  echo -e "\033[1;32mDone\033[0m"
else
  echo -e "\033[1;31mFailed\033[0m"
  echo "This script should be executed under ${ORACLE_OWNER}!"
  exit 1
fi

ROLLPACK_ID="000000000000"
LOGDIR="${LOGDIR}/${ROLLPACK_ID}"

source ./getpass "SYS"
source ./getpass "SYSTEM" "opt"

if [ "${DB_INSTALL_ENTERPRICE_MANAGER^^}" == "Y" ]; then
  source ./getpass "SYSMAN" "opt"
fi

./mk-dirs
./profile
./listener
source ./mk-init.ora
source ./mk-passfile
source ./add-database
source ./add-tablespaces
source ./add-catalog
source ./add-sqlplus
source ./add-jserver
source ./add-text
source ./add-xmldb
source ./add-multimedia
source ./add-olap
source ./add-spatial
source ./add-ols
source ./add-emrepo
source ./add-apex
source ./add-wbuilder
source ./add-extnet
source ./post-add
source ./archive-log
source ./mk-spfile
source ./em-setup
# sudo ./root
