#!/bin/bash

# This script will create spfile
# Author: Yuriy Lazutin
# Site: lazutin.info
# Location: Tomsk, Siberia
# Creation: 2021-apr-09
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

source ./rollpack-cmn
source ./print-info
source ./getpass "SYS"

if [ -z "${INIT_ORA}" ]; then
  source ./mk-init.ora
fi

sqlplus "sys/${SYS_PASS}" as SYSDBA &> "${LOGDIR}/mk-spfile-script.log" <<EOF
set verify off
set echo on

spool ${LOGDIR}/mk-spfile.log append
create spfile='${ORACLE_HOME}/dbs/spfile${ORACLE_SID}.ora' FROM pfile='${INIT_ORA}';
shutdown immediate;
startup;
spool off

exit
EOF

./mask-pass "${LOGDIR}/mk-spfile-script.log"
./mask-pass "${LOGDIR}/mk-spfile.log"

PrintInfo "Creating spfile"
