#!/bin/bash

# This script will request a passwords needed for ybusiness software installation.
# Author: Yuriy Lazutin
# Site: lazutin.info
# Location: Tomsk, Siberia
# Creation: 2021-apr-07
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

function GetPassword {
  if [ -z "$( eval echo \${$2})" ]; then
    for ((i=0; i < 3; i++)); do
      read -sp "Please enter password for ${1}: " ${2}
      echo
      if [ ! -z "$( eval echo \${$2})" ]; then
        export ${2}
        break
      fi
    done
  fi
}

function GetOptPassword {
  if [ -z "$( eval echo \${$2})" ]; then
    read -sp "Enter new password for ${1} (press Enter if it same as SYS): " ${2}
    echo
    if [ ! -z "$( eval echo \${$2})" ]; then
      export ${2}
      break
    fi
  fi
}


##########################
# Requesting a passwords #
##########################

GetPassword "${ORACLE_OWNER}" "ORACLE_PASS"
if [ -z "${ORACLE_PASS}" ]; then
  echo -e "\033[1;31mFailed. Password for ${ORACLE_OWNER} is empty.\033[0m"
  exit 1
fi

GetPassword "root" "ROOT_PASS"
if [ -z "${ROOT_PASS}" ]; then
  echo -e "\033[1;31mFailed. Password for root is empty.\033[0m"
  exit 1
fi

GetPassword "SYS" "SYS_PASS"
if [ -z "${SYS_PASS}" ]; then
  echo -e "\033[1;31mFailed. Password for SYS is empty.\033[0m"
  exit 1
fi

GetOptPassword "SYSTEM" "SYSTEM_PASS"
GetOptPassword "SYSMAN" "SYSMAN_PASS"
GetOptPassword "DBSNMP" "DBSNMP_PASS"
