#!/bin/bash

# This script will do post database creation steps.
# Author: Yuriy Lazutin
# Site: lazutin.info
# Location: Tomsk, Siberia
# Creation: 2021-apr-09
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

if [ -z "${YBUSINESS_SETUP_LEVEL}" ]; then
  export YBUSINESS_SETUP_LEVEL="script"
  source ../../conf
fi

source ./print-info
source ./getpass "SYS"

sed -i "s/SET TERMOUT on//" "${ORACLE_HOME}/rdbms/admin/catbundle.sql"
sed -i "s/insertScriptFile('B', 'SPOOL &' || 'spool_file');//" "${ORACLE_HOME}/rdbms/admin/catbundle.sql"
sed -i "s/SPOOL off//" "${ORACLE_HOME}/rdbms/admin/catbundle.sql"

sqlplus "sys/${SYS_PASS}" as SYSDBA &> "${LOGDIR}/post-add-script.log" <<EOF
set verify off
set echo on

spool ${LOGDIR}/post-db-creation.log append
@${ORACLE_HOME}/rdbms/admin/catbundle.sql psu apply;

select 'utl_recomp_begin: ' || to_char(sysdate, 'HH:MI:SS') from dual;
execute utl_recomp.recomp_serial();
select 'utl_recomp_end: ' || to_char(sysdate, 'HH:MI:SS') from dual;

spool off
exit
EOF

PrintInfo "Post database creation steps"
